%KAYNAK: http://www.mathworks.com/help/images/ref/imtransform.html
clear;
clc;
I = checkerboard;
udata = [0 1];  vdata = [0 1];

tform = maketform('projective',[ 0 0;  1  0;  1  1; 0 1],...
                               [-4 2; -8 -3; -3 -5; 6 3]);
                               
                               
[B,xdata,ydata] = imtransform(I, tform, 'bicubic', ...
                              'udata', udata,...
                              'vdata', vdata,...
                              'size', size(I),...
                              'fill', 128);
                          
subplot(1,2,1), imshow(I,'XData',udata,'YData',vdata), ...
axis on 
subplot(1,2,2), imshow(B,'XData',xdata,'YData',ydata), ...
axis on 