ResimOrjinal=imread('eight.tif');
logFiltresi=edge(ResimOrjinal,'log');
cannyFiltresi=edge(ResimOrjinal,'canny');
robertsFiltresi=edge(ResimOrjinal,'roberts');
prewittFiltresi=edge(ResimOrjinal,'prewitt');
sobelFiltresi=edge(ResimOrjinal,'sobel');
hLaplaceFiltresi=fspecial('laplacian');
%ResimOrjinal=im2double(ResimOrjinal);
laplaceFiltresi=imfilter(ResimOrjinal,hLaplaceFiltresi,'replicate');
figure;
subplot(3,3,2);
imshow(ResimOrjinal);
title('Resmin Orjinal Hali');
subplot(3,3,4);
imshow(logFiltresi);
title('1.Log Filtresi');
subplot(3,3,5);
imshow(cannyFiltresi);
title('2.Canny Filtresi');
subplot(3,3,6);
imshow(robertsFiltresi);
title('3.Roberts Filtresi');
subplot(3,3,7);
imshow(prewittFiltresi);
title('4.Prewitt Filtresi');
subplot(3,3,8);
imshow(sobelFiltresi);
title('5.Sobel Filtresi');
subplot(3,3,9);
imshow(laplaceFiltresi);
title('6.Laplace Filtresi');